trigger:
  branches:
    include: [ main ]

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AdvancedSecurity-Codeql-Init@1
    inputs:
      languages: 'javascript'

  - task: AdvancedSecurity-Codeql-Autobuild@1

  - task: AdvancedSecurity-Codeql-Analyze@1